/**
 * Named aliases over the generated contract types.
 *
 * `schema.d.ts` is generated by `npm run api:types` from `references/openapi.yaml`
 * and must never be hand-edited. This file exists only so features can import
 * `MsisdnPo` instead of `components["schemas"]["MsisdnPo"]`.
 */
import type { components } from "./schema";

type S = components["schemas"];

export type ApiError = S["Error"];
export type PageMeta = NonNullable<S["Paginated"]["meta"]>;

export type AdminProfile = S["AdminProfile"];
export type AdminOrganisation = S["AdminOrganisation"];
export type AdminAuthTokens = S["AdminAuthTokens"];
export type AdminRole = AdminProfile["role"];

export type CallPlan = S["CallPlan"];
export type Brand = S["Brand"];
export type DeviceModelRef = S["DeviceModelRef"];
export type DevicePartnerRef = S["DevicePartnerRef"];
export type MpxRef = S["MpxRef"];

export type MsisdnPo = S["MsisdnPo"];
export type MsisdnPoDetail = S["MsisdnPoDetail"];
export type MsisdnPoStatus = S["MsisdnPoStatus"];
export type IssuedMsisdn = S["IssuedMsisdn"];
export type SupplyValidation = S["SupplyValidation"];
export type SupplyResult = S["SupplyResult"];
export type PairingRow = S["PairingRow"];
export type PairingValidation = S["PairingValidation"];
export type PairingResult = S["PairingResult"];

export type DevicePo = S["DevicePo"];
export type DevicePoDetail = S["DevicePoDetail"];
export type DevicePoStatus = S["DevicePoStatus"];
export type Bundle = S["Bundle"];
export type AttachBundlesValidation = S["AttachBundlesValidation"];
export type AttachBundlesResult = S["AttachBundlesResult"];
export type StatusHistoryEntry = S["StatusHistoryEntry"];

export type DeliveryAddress = S["DeliveryAddress"];
export type CreateAddressBody = S["CreateAddressBody"];

export type Shipment = S["Shipment"];
export type CreateShipmentBody = S["CreateShipmentBody"];
export type ShipmentMilestoneType = S["ShipmentMilestoneType"];
export type GoodsReceipt = S["GoodsReceipt"];

export type StockLine = S["StockLine"];
export type StockBundle = S["StockBundle"];
export type Allocation = S["Allocation"];
export type AllocationDetail = S["AllocationDetail"];
export type AllocationMode = S["AllocationMode"];
export type CreateAllocationBody = S["CreateAllocationBody"];

export type AdminAccountExecutive = S["AdminAccountExecutive"];
export type AdminAccountExecutiveDetail = S["AdminAccountExecutiveDetail"];
export type BrandScope = S["BrandScope"];

/** Every list endpoint returns this shape. */
export interface Paginated<T> {
  data: T[];
  meta?: PageMeta;
}

/** The unpaginated `{ data: [...] }` envelope the reference endpoints use. */
export interface Envelope<T> {
  data: T[];
}
