# Production image for the FWA supply chain dashboard.
#
# Three stages so the runtime image carries neither the source nor the build
# toolchain: deps installs, builder compiles, runner ships `.next/standalone`.

FROM node:22-alpine AS deps
WORKDIR /app

# Only the manifests, so this layer is reused whenever dependencies are
# unchanged — which is most builds.
COPY package.json package-lock.json ./
RUN npm ci


FROM node:22-alpine AS builder
WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules
COPY . .

# `next build` runs `tsc` and ESLint. A type error or a lint error fails the
# image build rather than shipping a broken dashboard — the whole point of
# building here rather than on a laptop.
ENV NEXT_TELEMETRY_DISABLED=1
RUN npm run build


FROM node:22-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production \
    NEXT_TELEMETRY_DISABLED=1 \
    PORT=3000 \
    HOSTNAME=0.0.0.0

# Runs unprivileged. Nothing in this container writes to disk — there is no
# volume, because every piece of state lives in the API's database.
RUN addgroup --system --gid 10001 nodejs \
    && adduser --system --uid 10001 --ingroup nodejs nextjs

# The standalone server, then the two directories it deliberately does not
# bundle: `public/` (the brand assets and favicons) and the built client chunks.
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 3000

# `server.js` is generated by the standalone build; there is no `next start`
# here, and no `node_modules/.bin` to run it from.
CMD ["node", "server.js"]
